//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.WS2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ipca.pt/", ConfigurationName="WS2.FuncoesSoap")]
    public interface FuncoesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/Sum", ReplyAction="*")]
        int Sum(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.ipca.pt/Sum", ReplyAction="*")]
        System.IAsyncResult BeginSum(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndSum(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/Sub", ReplyAction="*")]
        int Sub(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.ipca.pt/Sub", ReplyAction="*")]
        System.IAsyncResult BeginSub(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndSub(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FuncoesSoapChannel : ConsoleClient.WS2.FuncoesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FuncoesSoapClient : System.ServiceModel.ClientBase<ConsoleClient.WS2.FuncoesSoap>, ConsoleClient.WS2.FuncoesSoap {
        
        private BeginOperationDelegate onBeginSumDelegate;
        
        private EndOperationDelegate onEndSumDelegate;
        
        private System.Threading.SendOrPostCallback onSumCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubDelegate;
        
        private EndOperationDelegate onEndSubDelegate;
        
        private System.Threading.SendOrPostCallback onSubCompletedDelegate;
        
        public FuncoesSoapClient() {
        }
        
        public FuncoesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FuncoesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncoesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncoesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<SumCompletedEventArgs> SumCompleted;
        
        public event System.EventHandler<SubCompletedEventArgs> SubCompleted;
        
        public int Sum(int x, int y) {
            return base.Channel.Sum(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSum(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSum(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSum(System.IAsyncResult result) {
            return base.Channel.EndSum(result);
        }
        
        private System.IAsyncResult OnBeginSum(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSum(x, y, callback, asyncState);
        }
        
        private object[] OnEndSum(System.IAsyncResult result) {
            int retVal = this.EndSum(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSumCompleted(object state) {
            if ((this.SumCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SumCompleted(this, new SumCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SumAsync(int x, int y) {
            this.SumAsync(x, y, null);
        }
        
        public void SumAsync(int x, int y, object userState) {
            if ((this.onBeginSumDelegate == null)) {
                this.onBeginSumDelegate = new BeginOperationDelegate(this.OnBeginSum);
            }
            if ((this.onEndSumDelegate == null)) {
                this.onEndSumDelegate = new EndOperationDelegate(this.OnEndSum);
            }
            if ((this.onSumCompletedDelegate == null)) {
                this.onSumCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSumCompleted);
            }
            base.InvokeAsync(this.onBeginSumDelegate, new object[] {
                        x,
                        y}, this.onEndSumDelegate, this.onSumCompletedDelegate, userState);
        }
        
        public int Sub(int x, int y) {
            return base.Channel.Sub(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSub(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSub(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSub(System.IAsyncResult result) {
            return base.Channel.EndSub(result);
        }
        
        private System.IAsyncResult OnBeginSub(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSub(x, y, callback, asyncState);
        }
        
        private object[] OnEndSub(System.IAsyncResult result) {
            int retVal = this.EndSub(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubCompleted(object state) {
            if ((this.SubCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubCompleted(this, new SubCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubAsync(int x, int y) {
            this.SubAsync(x, y, null);
        }
        
        public void SubAsync(int x, int y, object userState) {
            if ((this.onBeginSubDelegate == null)) {
                this.onBeginSubDelegate = new BeginOperationDelegate(this.OnBeginSub);
            }
            if ((this.onEndSubDelegate == null)) {
                this.onEndSubDelegate = new EndOperationDelegate(this.OnEndSub);
            }
            if ((this.onSubCompletedDelegate == null)) {
                this.onSubCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubCompleted);
            }
            base.InvokeAsync(this.onBeginSubDelegate, new object[] {
                        x,
                        y}, this.onEndSubDelegate, this.onSubCompletedDelegate, userState);
        }
    }
}
