//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML_WS_WindowsForm_Client.WS2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SumSub", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class SumSub : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sub {
            get {
                return this.SubField;
            }
            set {
                if ((this.SubField.Equals(value) != true)) {
                    this.SubField = value;
                    this.RaisePropertyChanged("Sub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS2.ICalcService")]
    public interface ICalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Sum", ReplyAction="http://tempuri.org/ICalcService/SumResponse")]
        int Sum(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICalcService/Sum", ReplyAction="http://tempuri.org/ICalcService/SumResponse")]
        System.IAsyncResult BeginSum(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndSum(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/SumAndSub", ReplyAction="http://tempuri.org/ICalcService/SumAndSubResponse")]
        XML_WS_WindowsForm_Client.WS2.SumSub SumAndSub(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICalcService/SumAndSub", ReplyAction="http://tempuri.org/ICalcService/SumAndSubResponse")]
        System.IAsyncResult BeginSumAndSub(int x, int y, System.AsyncCallback callback, object asyncState);
        
        XML_WS_WindowsForm_Client.WS2.SumSub EndSumAndSub(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceChannel : XML_WS_WindowsForm_Client.WS2.ICalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SumAndSubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SumAndSubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public XML_WS_WindowsForm_Client.WS2.SumSub Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((XML_WS_WindowsForm_Client.WS2.SumSub)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceClient : System.ServiceModel.ClientBase<XML_WS_WindowsForm_Client.WS2.ICalcService>, XML_WS_WindowsForm_Client.WS2.ICalcService {
        
        private BeginOperationDelegate onBeginSumDelegate;
        
        private EndOperationDelegate onEndSumDelegate;
        
        private System.Threading.SendOrPostCallback onSumCompletedDelegate;
        
        private BeginOperationDelegate onBeginSumAndSubDelegate;
        
        private EndOperationDelegate onEndSumAndSubDelegate;
        
        private System.Threading.SendOrPostCallback onSumAndSubCompletedDelegate;
        
        public CalcServiceClient() {
        }
        
        public CalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<SumCompletedEventArgs> SumCompleted;
        
        public event System.EventHandler<SumAndSubCompletedEventArgs> SumAndSubCompleted;
        
        public int Sum(int x, int y) {
            return base.Channel.Sum(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSum(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSum(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSum(System.IAsyncResult result) {
            return base.Channel.EndSum(result);
        }
        
        private System.IAsyncResult OnBeginSum(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSum(x, y, callback, asyncState);
        }
        
        private object[] OnEndSum(System.IAsyncResult result) {
            int retVal = this.EndSum(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSumCompleted(object state) {
            if ((this.SumCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SumCompleted(this, new SumCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SumAsync(int x, int y) {
            this.SumAsync(x, y, null);
        }
        
        public void SumAsync(int x, int y, object userState) {
            if ((this.onBeginSumDelegate == null)) {
                this.onBeginSumDelegate = new BeginOperationDelegate(this.OnBeginSum);
            }
            if ((this.onEndSumDelegate == null)) {
                this.onEndSumDelegate = new EndOperationDelegate(this.OnEndSum);
            }
            if ((this.onSumCompletedDelegate == null)) {
                this.onSumCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSumCompleted);
            }
            base.InvokeAsync(this.onBeginSumDelegate, new object[] {
                        x,
                        y}, this.onEndSumDelegate, this.onSumCompletedDelegate, userState);
        }
        
        public XML_WS_WindowsForm_Client.WS2.SumSub SumAndSub(int x, int y) {
            return base.Channel.SumAndSub(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSumAndSub(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSumAndSub(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public XML_WS_WindowsForm_Client.WS2.SumSub EndSumAndSub(System.IAsyncResult result) {
            return base.Channel.EndSumAndSub(result);
        }
        
        private System.IAsyncResult OnBeginSumAndSub(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSumAndSub(x, y, callback, asyncState);
        }
        
        private object[] OnEndSumAndSub(System.IAsyncResult result) {
            XML_WS_WindowsForm_Client.WS2.SumSub retVal = this.EndSumAndSub(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSumAndSubCompleted(object state) {
            if ((this.SumAndSubCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SumAndSubCompleted(this, new SumAndSubCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SumAndSubAsync(int x, int y) {
            this.SumAndSubAsync(x, y, null);
        }
        
        public void SumAndSubAsync(int x, int y, object userState) {
            if ((this.onBeginSumAndSubDelegate == null)) {
                this.onBeginSumAndSubDelegate = new BeginOperationDelegate(this.OnBeginSumAndSub);
            }
            if ((this.onEndSumAndSubDelegate == null)) {
                this.onEndSumAndSubDelegate = new EndOperationDelegate(this.OnEndSumAndSub);
            }
            if ((this.onSumAndSubCompletedDelegate == null)) {
                this.onSumAndSubCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSumAndSubCompleted);
            }
            base.InvokeAsync(this.onBeginSumAndSubDelegate, new object[] {
                        x,
                        y}, this.onEndSumAndSubDelegate, this.onSumAndSubCompletedDelegate, userState);
        }
    }
}
